name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取代码

      - name: Set up Python
        uses: actions/setup-python@v2  # 设置 Python 环境
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-cors beautifulsoup4 requests flask-freeze

      - name: Generate static files
        run: |
          python app.py  # 生成静态文件

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 使用 gh-pages 部署
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token
          publish_dir: ./build  # 静态文件目录