name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd templates
          if [ -f package.json ]; then
            npm install
          else
            echo "package.json not found in templates directory"
            exit 1
          fi

      - name: Build project
        run: |
          cd templates
          if [ -f package.json ]; then
            npm run build
          else
            echo "Build script not found"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./templates