name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # 触发工作流的分支，根据实际情况修改

  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 使用 actions/checkout@v3 或更高版本

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 根据项目需要选择 Node.js 版本

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./templates