name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Build project
      run: python fetch.py

    - name: Deploy to Server
      env:
        DEPLOY_SERVER: server
        DEPLOY_USER: cool-chicken
        DEPLOY_PATH: /path/to/deploy
      run: |
        scp -r ./templates/index.html $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH/templates/
        ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && ./deploy.sh"